"use client";
import Image from "next/image";

import "./globals.css";
import { Banner, useBanner } from "@/components/Banner";
import { FOOTER_LINKS } from "@/utils/constants";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"flex flex-col justify-between min-h-screen"}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
